- name: ESLint checks
  uses: gimenete/eslint-action@1.0
- name: Python Style Checker
  uses: andymckay/pycodestyle-action@0.1.3
- name: Upgrade to Python 3
  uses: cclauss/Upgrade-to-Python3@0.1.0
- name: Pyflakes Syntax Checker
  uses: lgeiger/pyflakes-action@v1.0.1
- name: GitHub Action for cpplint
  uses: cclauss/GitHub-Action-for-cpplint@0.0.6
